### ISSUE TITLE
Search missing results

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/website#105]
When I search for 'boston', I get the boston dataset in the suggestions, but actually running the search yields 0 results.

**Comment by janvanrijn** [comment]
Had something similar with "dexter" (dataset) today

2017-03-05 22:04 GMT+01:00 Joaquin Vanschoren <notifications@github.com>:

**Comment by joaquinvanschoren** [comment]
Fixed. Turned out some search options were deprecated in the new version of the search engine.
