### ISSUE TITLE
Optional Parameter evaluation_measure is left blank when it is not filled

### ISSUE THREAD

**Issue by janvanrijn** [openml/website#128]
Whereas I would expect it to be removed from the XML. 
e.g., https://test.openml.org/api/v1/task/20: I would expect this to be not there at all. <oml:evaluation_measures><oml:evaluation_measure/></oml:evaluation_measures></oml:input>

@giuseppec Would the R package like that, or will it break?

**Comment by giuseppec** [comment]
I quickly tried it out and it seems that the R package does not break when the field is removed.

**Comment by joaquinvanschoren** [comment]
@janvanrijn seems like we can just remove it then and close this issue?

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#566
