### ISSUE TITLE
Simplify run upload

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/website#131]
Since we simplified the model for evaluations, we no longer need the 'flow' element from the run upload. I guess that this can be removed from the XML, or phased out?

**Comment by janvanrijn** [comment]
This is legacy. We can not remove it yet, as the mlr connector requires
this field.

2017-05-02 23:52 GMT+02:00 Joaquin Vanschoren <notifications@github.com>:

**Comment by joaquinvanschoren** [comment]
Shall we stop checking for it, so they can phase it out?
Or leave everything as is until API v2?
