### ISSUE TITLE
Cannot sort flows

### ISSUE THREAD

**Issue by mfeurer** [openml/website#137]
Because the dropdown menu doesn't appear:

![image](https://cloud.githubusercontent.com/assets/5320498/26301505/ba38f342-3ee1-11e7-807a-2be888cdbe2a.png)

Browser: Firexfox 53.0.2 (64-bit) on Ubuntu 16.04.

**Comment by joaquinvanschoren** [comment]
Ah... that's because you are in the general search. If you select flows in the left menu you'll get the correct sorting fields. I guess I should remove the sorting option there because it doesn't make sense.

**Comment by joaquinvanschoren** [comment]
I changed the button. It will tell you to select a type and open the menu if you click it.
