### ISSUE TITLE
The search is not working so well

### ISSUE THREAD

**Issue by jakob-r** [openml/website#14]
For instance I was not able to find this data set http://openml.org/d/279 through the search via the term "meta" or even "meta_stream".

**Comment by joaquinvanschoren** [comment]
Weird. I've rebuild the index and it still isn't there. Somehow elasticsearch is choking on this one. I'll check it out.

**Comment by jakobbossek** [comment]
Is this fixed?

**Comment by jakob-r** [comment]
Works now.
