### ISSUE TITLE
Frontend does not allow downloading a flow XML

### ISSUE THREAD

**Issue by mfeurer** [openml/website#142]
There are only buttons for JSON and RDF (which, as a side remark, also does not work):

![image](https://cloud.githubusercontent.com/assets/5320498/26404990/1cb2f442-4094-11e7-901b-a371527cbb88.png)

**Comment by joaquinvanschoren** [comment]
I added XML as well.
RDF works only on the production server. It requires a library that's not installed on the test server yet.
