### ISSUE TITLE
Created task --> weird messages on my screen

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#147]
After creating [task 146542](https://www.openml.org/t/146542) I saw this on the top of the page:
![image](https://cloud.githubusercontent.com/assets/14146757/26833464/d0225caa-4ad2-11e7-9fa6-0a2e7384a394.png)

And this at the bottom:
![image](https://cloud.githubusercontent.com/assets/14146757/26833547/135a3498-4ad3-11e7-8edf-b443d1e703f1.png)

**Comment by joaquinvanschoren** [comment]
Fixed.
