### ISSUE TITLE
Sorting of tasks does not work properly

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#150]
I want to sort supervised regression tasks by number of runs. This is what I get:
![image](https://user-images.githubusercontent.com/14146757/26875915-34d86ad4-4b84-11e7-8dbf-36a6f2fd75cf.png)
which is probably not correct.

Possibly connected to #137

**Comment by joaquinvanschoren** [comment]
This is actually correct. Sadly, we don't have many regression results yet, and not all QSAR results are uploaded (but they should be soon since the paper is accepted).
