### ISSUE TITLE
People: Two fields to sort by "highest activity" 

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#153]
On https://www.openml.org/search?type=user when I want to sort people I see "Highest Activity" twice:
![image](https://user-images.githubusercontent.com/14146757/27677855-6319e5e0-5cb3-11e7-8843-b2392c17261f.png)

**Comment by joaquinvanschoren** [comment]
Thanks.
Fix pushed.
https://github.com/openml/website/pull/174
