### ISSUE TITLE
limit size of listing functions

### ISSUE THREAD

**Issue by janvanrijn** [openml/website#157]
this is done for runs and evals, but should also be done for flows, data and setups. Otherwise php code crashes without proper error msg

**Comment by janvanrijn** [comment]
Particularly complicated for setup listing, due to the query structure

**Comment by janvanrijn** [comment]
Fixed for setups. Now only the data, tasks and flows left.

**Comment by joaquinvanschoren** [comment]
I believe this has been done?

**Comment by joaquinvanschoren** [comment]
@janvanrijn can you check and close?

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#558
