### ISSUE TITLE
dead link to data characteristics

### ISSUE THREAD

**Issue by amueller** [openml/website#162]
There's a link to data characteristics on this page:
https://www.openml.org/guide

it links to an empty search result:
https://www.openml.org/search?q=+type%3Adata_quality&type=measure

I'm not sure what the intention was.

**Comment by joaquinvanschoren** [comment]
Thanks, that should have been:
https://www.openml.org/search?q=+measure_type%3Adata_quality&type=measure

Fixed the link in a PR

**Comment by amueller** [comment]
thanks, feel free to close (or once merged).

**Comment by joaquinvanschoren** [comment]
Merged, thanks.
