### ISSUE TITLE
searching by feature type

### ISSUE THREAD

**Issue by amueller** [openml/website#164]
Is there a way to search datasets by feature type via the website?
If so, it's not clear to me. It's also not entirely clear to me what possible feature types are.
From [here](https://github.com/openml/OpenML/blob/master/Java/OpenmlWebapplication/src/main/java/org/openml/webapplication/features/ExtractFeatures.java#L103) it looks like there are "numeric", "nominal", "string" and "unknown". Is that documented somewhere?

**Comment by joaquinvanschoren** [comment]
What is the purpose of the search? Do you need datasets with at least one 'nominal' features, or datasets with only 'nominal' features?

In principle, OpenML allows free-form datatypes. In practice, only ARFF datatypes are stored after parsing the dataset.

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#556
