### ISSUE TITLE
Link to rest tutorial doesn't work

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#172]
When I go to https://www.openml.org/guide/api and click on "Rest Tutorial" I get here

https://www.openml.org/guide/rest_tutorial

which is empty.

**Comment by joaquinvanschoren** [comment]
Thanks, PR with a fix submitted. Should be online soon.

What do you think of the new layout thus far?
I also cleaned up the Wiki on GitHub.

**Comment by HeidiSeibold** [comment]
I like it! Very fancy :cake:
