### ISSUE TITLE
Run rendering broken

### ISSUE THREAD

**Issue by mfeurer** [openml/website#179]
See https://www.openml.org/r/2347443 and compare for https://www.openml.org/api/v1/run/2347443. You can see that for example the username is not rendered, the flow is not rendered, the discussion is not rendered, the task number is not rendered etc.

**Comment by mfeurer** [comment]
Same here: https://www.openml.org/r/473350

**Comment by joaquinvanschoren** [comment]
These runs don't exist anymore. Probably a stale index.
Seems ok now.
