### ISSUE TITLE
No option to filter regression data sets

### ISSUE THREAD

**Issue by jakob-r** [openml/website#19]
To find regression data sets one has to go over task type, tasks and so on...
I would like to be able to search for them specificaly.
Unfortunately
http://openml.org/search?type=data&q=+NumberOfClasses%3A0 doesn't do the trick :grinning:

**Comment by joaquinvanschoren** [comment]
Hmm, good call. I'll add a filter 'used in tasks of type ...'

**Comment by joaquinvanschoren** [comment]
Closing. You can filter tasks by their task type, then download the corresponding datasets?
