### ISSUE TITLE
Improve evaluation measure explanation

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#197]
When I look at e.g. the mean absolute error
https://www.openml.org/a/evaluation-measures/mean-absolute-error
it is not super useful.

I think we should
- clean it up with
   - no unrendered formulas
   - correct specification of the minimum and maximum
   - a working link to the code 
- add information on which task type this can/should be used for.

**Comment by WilliamRaynaut** [comment]
I did most of this on the TEST db, it could be rolled to production...

**Comment by HeidiSeibold** [comment]
Oh that's awesome! @janvanrijn @joaquinvanschoren can we ship this? :) :cake:

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#547
