### ISSUE TITLE
Wrong citation of dataset covertype v.1

### ISSUE THREAD

**Issue by jakob-r** [openml/website#20]
I am not able to follow your citation on http://openml.org/d/180

**Comment by joaquinvanschoren** [comment]
What do you mean? The 3 papers listed in the description?

**Comment by jakob-r** [comment]
The dataset has 110`393 observations.
The given [UCI source](https://archive.ics.uci.edu/ml/datasets/Covertype) has 500k.

**Comment by joaquinvanschoren** [comment]
You are right. The origin of this one is unknown to me. It looks like
someone did a 19% subsampling of the original data set. The original
dataset is version 4: http://openml.org/d/1596

I updated the description.

**Comment by jakob-r** [comment]
Thanks. From my side it can be closed.
