### ISSUE TITLE
Drastically expand bootcamp or provide user guide

### ISSUE THREAD

**Issue by amueller** [openml/website#201]
I'm still frequently struggling to understand core concepts in openml.
I think we need to drastically expand the bootcamp or provide another language-agnostic user guide.
The REST API docs are probably the most complete, but they don't contain any semantics (and probably shouldn't).
For example if I want to know what the difference between data set qualities and data set features is, I wouldn't know where to look. And I'm not sure the docs have a complete list of either of them.

(The issue is inspired by me not being able to find any documentation of what a "version" of a data set is).

**Comment by amueller** [comment]
So are you ok with expanding the bootcamp? I might send a PR about that...

**Comment by joaquinvanschoren** [comment]
Yes, thank you!
