### ISSUE TITLE
rest docs have broken links

### ISSUE THREAD

**Issue by amueller** [openml/website#208]
If you go to https://www.openml.org/api_docs#!/data/get_data_list
and click on the get button or the text next to it, you are redirected to ``https://www.openml.org/#!/data/get_data_list`` which should probably be ``https://www.openml.org/api_docs#!/data/get_data_list`` instead (it takes you to the landing page)

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#541
