### ISSUE TITLE
Use case: get similar task types

### ISSUE THREAD

**Issue by janvanrijn** [openml/website#216]
Suppose I want to solve the OpenML100, but not on CV tasks but on the holdout set. This is currently not (easily) supported

**Comment by janvanrijn** [comment]
For now, this query kind of solves it, but it should be integrated in the API:

`SELECT sd.task_id, d.id, ep.value, e.value FROM dataset_tag d LEFT JOIN task_inputs sd ON sd.value = d.id AND sd.input = "source_data" LEFT JOIN task_inputs ep ON ep.task_id = sd.task_id AND ep.input = "estimation_procedure" LEFT JOIN task_inputs e ON e.task_id = sd.task_id AND e.input = "evaluation_measure" WHERE d.tag = "OpenML100" AND ep.value = 6`

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#533
