### ISSUE TITLE
junk after document element: line 5, column 0

### ISSUE THREAD

**Issue by janvanrijn** [openml/website#221]
dataset uploading breaks when you also tag the dataset in the process (probably also runs, flows, tasks)

**Comment by joaquinvanschoren** [comment]
Don't understand. How do you tag a dataset while uploading?
Is this a frontend or API issue?

**Comment by janvanrijn** [comment]
API. I will fix it ASAP

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#531

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#535
