### ISSUE TITLE
flow/exists: Mandatory fields not present.

### ISSUE THREAD

**Issue by giuseppec** [openml/website#23]
Hi,

I tried this as GET: 
```
http://api_new.openml.org/v1/flow/exists/?api_key=MYKEY&name=classif.randomForest&external_version=R_6fea982893af0f5d1607b908a9d7bf40
```
and using the POST request : 
```
http://api_new.openml.org/v1/flow/exists/?api_key=MYKEY
```
with `name=classif.randomForest&external_version=R_6fea982893af0f5d1607b908a9d7bf40` in the body of POST request.

For both GET and POST, it tells me:
```
<oml:error xmlns:oml="http://openml.org/openml">
	<oml:code>330</oml:code>
	<oml:message>Mandatory fields not present.</oml:message>
	</oml:error>
```

During the Workshop this worked for me. Did something changed?

**Comment by joaquinvanschoren** [comment]
Hi Giuseppe,

flow/exists in now updated to the new API, use:
http://www.openml.org/api_new/v1/flow/exists/classif.randomForest/R_6fea982893af0f5d1607b908a9d7bf40

**Comment by giuseppec** [comment]
Thanks, works now.
