### ISSUE TITLE
Upgrade server PHP to at least 5.5.0

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/website#24]
I get Fatal error: Class 'CurlFile' not found ... because the server runs an older version of PHP. I now have to use the pre-CurlFile way to upload data, which is deprecated.

Can we please upgrade, because it is very hard to develop if my local PHP version is newer.

**Comment by giuseppec** [comment]
Is this the reason why I am getting this site when visiting openml:
![unbenannt](https://cloud.githubusercontent.com/assets/4238748/9796161/f9ce266a-57f4-11e5-91d0-317f81773db6.PNG)

**Comment by joaquinvanschoren** [comment]
Yes. Terribly sorry. Working on it.

**Comment by joaquinvanschoren** [comment]
Done. Closing.
