### ISSUE TITLE
Task with arff containing "Task not providing datasplits."

### ISSUE THREAD

**Issue by giuseppec** [openml/website#25]
Hi,

there seem to be serveral tasks that contain a non-valid `.arff` files in the data split node. 
For example the XML for task 7529 contains a line `<oml:data_splits_url>http://www.openml.org/api_splits/get/7529/Task_7529_splits.arff</oml:data_splits_url>`. The arff file (link: http://www.openml.org/api_splits/get/7529/Task_7529_splits.arff) contains only one linke: `Task not providing datasplits.` I think this is a non valid arff format and causes issues in R because we will download and open each arff file when there is a link in the `oml:data_splits_url` node.
I can do a dirty `tryCatch` error handling but I think this should be solved from server side?

**Comment by berndbischl** [comment]
should this really be in the tracker for "website"? and not the main tracker?

**Comment by joaquinvanschoren** [comment]
Hmm, that task uses 'testontrainingdata' as the evaluation procedure, which is possible for clustering.
I would propose to simply remove it the splits url from the task description? Or would you need a splits file with the whole dataset as a single split?

**Comment by giuseppec** [comment]
I would prefer not to have an .arff file. So removing the url or adding a string like `No URL` to the url field (I think I've seen this, please check if I am right) is fine for me. Also, I would like to know all possible values the `oml:data_splits_url` field can have (since I have also seen strings instead of urls).
And: please make sure that this is consistent for each clustering task. All clustering tasks currently seem to have a `oml:data_splits_url` field linking to an .arff file that contains the string `Task not providing datasplits.`.

**Comment by giuseppec** [comment]
Here another one: http://www.openml.org/api_splits/get/5741/Task_5741_splits.arff

**Comment by giuseppec** [comment]
I'll close this here, we can continue here: https://github.com/openml/OpenML/issues/338
