### ISSUE TITLE
New api does not lookup estimation procedure in task type

### ISSUE THREAD

**Issue by jaksmid** [openml/website#29]
http://www.openml.org/api_new/v1/tasktype/1
This retrieves the task type, however, in the estimation procedure the values are not filled properly:

<oml:input name="estimation_procedure">
<oml:estimation_procedure>
<oml:type>[LOOKUP:estimation_procedure.type]</oml:type>
<oml:data_splits_url>
[CONSTANT:base_url]api_splits/get/[TASK:id]/Task_[TASK:id]_splits.arff
</oml:data_splits_url>
<oml:parameter name="number_repeats">[LOOKUP:estimation_procedure.repeats]</oml:parameter>
<oml:parameter name="number_folds">[LOOKUP:estimation_procedure.folds]</oml:parameter>
<oml:parameter name="percentage">[LOOKUP:estimation_procedure.percentage]</oml:parameter>
<oml:parameter name="stratified_sampling">[LOOKUP:estimation_procedure.stratified_sampling]</oml:parameter>
</oml:estimation_procedure>
</oml:input>

**Comment by janvanrijn** [comment]
Dear Jakob,

This is the task type you're looking at, and serves as a template for the
tasks. If you want to see the values filled in, please see:

http://www.openml.org/api_new/v1/task/1 (or change 1 to your task number)

Cheers,
Jan

2015-10-08 18:30 GMT+02:00 Jakub Šmíd <notifications@github.com>:

**Comment by jaksmid** [comment]
Hi Jan,

thanks for the message.
However, there is currently no task type id returned, there is just something like:
[CONSTANT:base_url]api_splits/get/[TASK:id]/Task_[TASK:id]_splits.arff returned, so no means how to perform the lookup.

**Comment by jaksmid** [comment]
Oh, I see it now. Thanks for the comment. I thought that TaskType specifies the estimation procedure, but it just specifies that you need to specify one when creating task of that type.

**Comment by jaksmid** [comment]
Maybe it would be a nice thing to rename the Estimation procedure in task type to estimation procedure template, so its clear.

**Comment by jaksmid** [comment]
Now, there are two entities in oml:
estimation_procedure and estimationprocedure. Its not clear by looking at them which one is a template. Hence the confusion.
