### ISSUE TITLE
oml task_type inconsistent

### ISSUE THREAD

**Issue by jaksmid** [openml/website#30]
The results of tasktype get by id and list task types are inconsistent.
Both return oml:task_type.
The list query does not return some fields, however it return creators. The query by id returns contributors, not creators and it returns also fields like output and input.

Furthemore, the creators are also not consistent, sometimes it is Name1, Name2,
other time it is "Name1","Name2".

Make this more consistent.
Reference:
http://www.openml.org/api_new/v1/tasktype/1
http://www.openml.org/api_new/v1/tasktype/list

**Comment by jakobbossek** [comment]
This is no website issue.
However, I think this is even solved.

**Comment by jaksmid** [comment]
It is not solved as you can easily check by visiting the links.
How is this not a website issue? Isnt the API part of the website?

Thanks,
Jakub

**Comment by joaquinvanschoren** [comment]
Technically yes, but API issues are typically reported in the general issue
tracker. I'll fix this soon.

**Comment by jaksmid** [comment]
I see, I will report API related bugs in the general issue tracker further on.

Let me know if I can be of any help.
Regards,
Jakub
