### ISSUE TITLE
Runs not being shown in task 2075

### ISSUE THREAD

**Issue by DraXus** [openml/website#32]
There are 558 runs for the task 2075, but there is no plot available in http://www.openml.org/t/2075#!taskruns

**Comment by joaquinvanschoren** [comment]
I did an index rebuild yesterday. They may have disappeared from the website for a few minutes. Looks ok now?

**Comment by DraXus** [comment]
Brilliant, thanks! BTW, the absence of scrollbars is a bit annoying :(

On 22 October 2015 at 21:20, Joaquin Vanschoren <notifications@github.com>
wrote:

> I did an index rebuild yesterday. They may have disappeared from the
> website for a few minutes. Looks ok now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openml/website/issues/32#issuecomment-150345141>.
>



-- 
Web: http://draxus.org

**Comment by joaquinvanschoren** [comment]
Where do you want scrollbars?

**Comment by DraXus** [comment]
Oh, I just noticed that there are scrollbars in firefox, but not in Chrome.
I can open a different issue for that.

On 23 October 2015 at 13:20, Joaquin Vanschoren <notifications@github.com>
wrote:

> Where do you want scrollbars?
>
> On Fri, Oct 23, 2015 at 2:08 PM Manuel Martín <notifications@github.com>
> wrote:
>
> > Brilliant, thanks! BTW, the absence of scrollbars is a bit annoying :(
> >
> > On 22 October 2015 at 21:20, Joaquin Vanschoren <
> notifications@github.com>
> > wrote:
> >
> > > I did an index rebuild yesterday. They may have disappeared from the
> > > website for a few minutes. Looks ok now?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/openml/website/issues/32#issuecomment-150345141>.
> > >
> >
> >
> >
> > --
> > Web: http://draxus.org
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openml/website/issues/32#issuecomment-150555603>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openml/website/issues/32#issuecomment-150557304>.
>



-- 
Web: http://draxus.org
