### ISSUE TITLE
Scrollbars are missing in Chrome

### ISSUE THREAD

**Issue by DraXus** [openml/website#33]
Google Chrome (Linux)
![chrome](https://cloud.githubusercontent.com/assets/2436/10692811/dab4c79e-798b-11e5-8b27-e0b5ef95510b.png)

Firefox (Linux)
![firefox](https://cloud.githubusercontent.com/assets/2436/10692810/dab25144-798b-11e5-9a73-9cbec4b7ce12.png)

**Comment by joaquinvanschoren** [comment]
This is intentional, and defined in CSS. Firefox just ignores that, Chrome
follows specification.
I find them especially ugly in the left menu bar...

Do you really find the scrollbars easier to use?

**Comment by DraXus** [comment]
Interesting! :smile: 

They could be uglier, but definitely much more handy than scrolling with the mouse in long pages like those. I also find confusing that the sidebar is detached from the main page (reminds me to old frames sites :)), but that's a minor issue.

**Comment by joaquinvanschoren** [comment]
I will allow them again but am on a train right now.
With detached you mean that it scrolls separately? This is because of
mobile devices. It is not a frame. If you make the window narrow and
reload, you'll see that it is hidden and only slides over the main window
on request. Other websites like google inbox do the same :). It is also
nicer on long pages that the submenu does not disappear as you scroll down,
no?

**Comment by DraXus** [comment]
Now that I see Google Inbox I see the resemblance ;) I agree that scrollbars looks ugly in Firefox, but the ones from Inbox looks quite nice (not sure how difficult would be to implement those):
![inbox](https://cloud.githubusercontent.com/assets/2436/10696633/f97305aa-79a0-11e5-9775-7dca3861ba86.png)

In any way this is just my personal opinion, please don't make changes only based on that.

**Comment by joaquinvanschoren** [comment]
Hi Manuel,

The scrollbars are back. Is it better now?

Cheers,
Joaquin

**Comment by DraXus** [comment]
Fantastic. I found it much easier to browse. Thanks!

Manuel

On 3 November 2015 at 14:26, Joaquin Vanschoren <notifications@github.com>
wrote:

> Hi Manuel,
>
> The scrollbars are back. Is it better now?
>
> Cheers,
> Joaquin
>
> On Fri, Oct 23, 2015 at 5:14 PM Manuel Martín <notifications@github.com>
> wrote:
>
> > Now that I see Google Inbox I see the resemblance ;) I agree that
> > scrollbars looks ugly in Firefox, but the ones from Inbox looks quite
> nice
> > (not sure how difficult would be to implement those):
> > [image: inbox]
> > <
> https://cloud.githubusercontent.com/assets/2436/10696633/f97305aa-79a0-11e5-9775-7dca3861ba86.png
> >
> >
> > In any way this is just my personal opinion, please don't make changes
> > only based on that.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openml/website/issues/33#issuecomment-150604556>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openml/website/issues/33#issuecomment-153370558>.
>



-- 
Web: http://draxus.org

**Comment by joaquinvanschoren** [comment]
I did one more thing to make the menu scrollbars nicer. Does this still look good? If so you can close the issue :).

**Comment by DraXus** [comment]
Now the scrollbar in the left menu has gone :(

**Comment by joaquinvanschoren** [comment]
And you don't see another (finer) scrollbar?

**Comment by DraXus** [comment]
Not at all 
![leftsidebar](https://cloud.githubusercontent.com/assets/2436/10938954/06193e9c-82f6-11e5-8b1a-d1bdd65cce48.png)

**Comment by joaquinvanschoren** [comment]
Weird. Which OS are you using? This is standard javascript so you should
see it. Did you do a hard page reload?

**Comment by DraXus** [comment]
Hard reload did the trick, sorry for not trying that before :)
