### ISSUE TITLE
Profile stats are not being updated

### ISSUE THREAD

**Issue by rgmantovani** [openml/website#34]
Hi, 

I have already run a lot of experiments and my profile stats are not being updated according to those uploads.

![screen shot 2015-12-01 at 6 05 59 pm](https://cloud.githubusercontent.com/assets/5933552/11507846/357a2db6-9856-11e5-962a-8b8d5f94b487.png)

But when I access the Run activities in the left menu I can see all of them.

![screen shot 2015-12-01 at 6 04 09 pm](https://cloud.githubusercontent.com/assets/5933552/11507796/fb67e2e4-9855-11e5-9065-d3b8f01c5f02.png)

**Comment by joaquinvanschoren** [comment]
Thanks. Fixed!
