### ISSUE TITLE
After submission of a dataset Cronjob never kicks in

### ISSUE THREAD

**Issue by zardaloop** [openml/website#36]
When you submit a new dataset, the cronjob never kicks in and as a result it get stuck with only showing 

> "Data features are not analyzed yet. Refresh the page in a few minutes."

I have asked couple of time @joaquinvanschoren to help me by running the cronjob manually but I though since that happened couple of time maybe log something here. :)

**Comment by joaquinvanschoren** [comment]
This was caused by one dataset blocking the process. I changed it so that
such datasets don't block the cronjob.
