### ISSUE TITLE
Anchors to headers

### ISSUE THREAD

**Issue by mfeurer** [openml/website#42]
I want to link to the dataset section in the OpenML guide from the python API. So far, I can only link [openml.org/guide](openml.org/guide), it would be great if I could link openml.org/guide#data

**Comment by joaquinvanschoren** [comment]
There is suggestion in #57 to redesign the guide, and have a series of blog posts discussing various aspects of OpenML. You would then also have direct links to aspects such as datasets, and room for much more detail.

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#593
