### ISSUE TITLE
Data set pages keep saying "Loading wiki" but nothing happens

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#54]
![screenshot from 2016-05-31 15 59 49](https://cloud.githubusercontent.com/assets/14146757/15677037/d1c7532a-2748-11e6-87ff-a81c1e81bb8a.png)

Screenshot is from http://www.openml.org/d/1228 but I tried also other data sets. I tried both on Firefox and Chrome.

**Comment by joaquinvanschoren** [comment]
There's something wrong with the automatic start of the wiki. If someone
restarts the server I have to start the wiki manually. I'll look at it
again tonight...
