### ISSUE TITLE
Sorting people

### ISSUE THREAD

**Issue by dominikkirchhoff** [openml/website#55]
Hi,

this should be a minor and "fast to fix" issue. [Here](http://www.openml.org/search?type=user), you can sort people by many attributes.

- "Highest Activity" appears twice—one of them should be "Lowest Activity".

- The default order is "Most recent". However, one obviously can't invert the order. Also, as soon as you select another sorting, you can't sort the people by their date of joining without, e.g., using the browser's back button. It wouldn't hurt to add "Most recent" and "Least recent" to the drop down menu, would it? At least I just wondered who were the "oldest" members and didn't want to scroll through the whole list.

**Comment by jakobbossek** [comment]
+1 Yes. This is a simple copy and paste error. One of these links sorts in ascending and the other in descending order.

**Comment by jakobbossek** [comment]
Should be fixed in seconds

**Comment by joaquinvanschoren** [comment]
Fixed. Thanks.
