### ISSUE TITLE
Problem with task 13918

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#58]
http://www.openml.org/api_splits/get/13918/Task_13918_splits.arff

is empty. In contrast

http://www.openml.org/api_splits/get/10104/Task_10104_splits.arff

works.

**Comment by joaquinvanschoren** [comment]
@janvanrijn: I can't see where the problem is. How do we link the data splits to a task?

**Comment by jakobbossek** [comment]
This is no website issue.

**Comment by joaquinvanschoren** [comment]
faulty task. removed.
