### ISSUE TITLE
OpenML main page

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#59]
I went hiking with a friend yesterday who works in UX. We talked a little about what the front page should look like, to draw people into using the platform.

His main point was, that it is important, to give the visitors a short (without scrolling) and clear information on what is the **benefit for them** if they sign up.
To know how whe get them to sign up, we need to specify what our **target audience** is on this first page.

A good example is maybe figshare https://figshare.com/

Since we have several target audiences (applied researchers, machine learners, teachers,...) it might not be just as easy. 
What I can think of now would be e.g.:
- Applied researcher: Publish data and have others find meaningful information / do the analysis for you.
- Machine learner / statistician: Find and solve interesting problems, publish your algorithm, get credit 
- Teacher: Set up challenges for students to solve, Offer an easy way for students to discover powerful algorithms

**Comment by joaquinvanschoren** [comment]
FigShare has links for specific audiences (institutions, publishers) that
lead to dedicated pages with benefits for them (but then they run straight
to a contact box). On OpenML we could actually put dedicated resources
there, such as tutorials for users and teaching materials for teachers.

On the other hand, I love the google docs page, which has clean dedicated
subpages to explain user-specific features:
https://www.google.com/docs/about/

We could do something similar to this, using specific pages for data,
tasks, flows, runs, studies, ... each with a short overview of features
which are now hidden in the guide or not discussed at all, e.g.:
* Data: easy to upload or reference from elsewhere, upload
programmatically, quick overviews of features on website, wiki,
meta-features for finding similar datasets, tagging, links to tasks/models
built on the data, crowdsource analysis, bots that automatically build
models on data, sharing in teams, DOIs?,...

We could combine this with a front page that explicitly mentions audiences
(scientists, ML researchers, teachers,...) with links to some of the
features interesting to them. What do you think?

**Comment by jakobbossek** [comment]
My opinion:
Fist, I like [google docs](https://www.google.com/docs/about/) and I love minimalistic, content-orientated design.
Second, I somehow like OpenML's current color schema although I usually stick to grayscale colors.
Third, I agree with @HeidiSeibold and her unknown friend, that we should redesign the homepage. The first thing I see are some circles with numbers of datasets/flows/tasks/.... However, it is statistically proved, that users have a very restricted attention span and leave a website if they did not stumble upon useful information within seven seconds. We need to capture users on the first spot!
