### ISSUE TITLE
Error: profile editing

### ISSUE THREAD

**Issue by jakobbossek** [openml/website#60]
Trying to update my profile, i.e., modifying the image and the description.
I get the error "The Password Confirmation field does not match the password field." even though I did not change the password at all. By the way: I got the same error if I enter the same password into all the old, new and new confirmation password fields.
Had some 🍺, but I am quite sure, that this is not my fault 😆

**Comment by joaquinvanschoren** [comment]
You are right. It checks too strictly. Fixed now. 
Thanks, I'll buy you a 🍺

**Comment by jakobbossek** [comment]
> You are right. It checks too strictly. Fixed now. 

Thanks 👍 

> Thanks, I'll buy you a 🍺

Ah, looking forward to the next awesome openml workshop 😉
