### ISSUE TITLE
No version selection if there is only one version

### ISSUE THREAD

**Issue by jakobbossek** [openml/website#63]
If there is only one version of a dataset it makes no sense to select the "list of datasets".
<img width="461" alt="bildschirmfoto 2016-09-19 um 02 24 51" src="https://cloud.githubusercontent.com/assets/4079979/18620334/816f82a2-7e10-11e6-87dc-be32a364f175.png">

**Comment by joaquinvanschoren** [comment]
prefer to keep it this way for consistency?
