### ISSUE TITLE
Links in guide to REST API do not work

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#66]
http://www.openml.org/guide

When I click on any of the first three links below REST API, it does not get me to where I want it to get me, but to the main page.

**Comment by joaquinvanschoren** [comment]
The link to the API reference was indeed outdated. The others seem to work, though?

**Comment by HeidiSeibold** [comment]
When I click on REST Tutorial or JSON Endpoints it gets me to the main page still

**Comment by joaquinvanschoren** [comment]
Which browser are you using? For me it works in Chrome, Firefox and Safari.
Did the page finish loading before you clicked the link?

**Comment by HeidiSeibold** [comment]
Ah, the problem does not appear when I just click on the link but only if I open the link in a new tab (which I almost always do).

**Comment by joaquinvanschoren** [comment]
Right. I have fixed them so that they also work when reloading.

**Comment by HeidiSeibold** [comment]
Perfect :)
