### ISSUE TITLE
license/waiver info links to incorrect page

### ISSUE THREAD

**Issue by egonw** [openml/website#73]
As found for this [data set](http://www.openml.org/d/1493):

![image](https://cloud.githubusercontent.com/assets/26721/20214353/fbc557b2-a80d-11e6-8ee8-b8f8de2dfeae.png)

The link behind "Publicly available" point to a tool to select a license/waiver and is not the link for a particular license/waiver. If CCZero is meant, please use https://creativecommons.org/publicdomain/zero/1.0/

**Comment by joaquinvanschoren** [comment]
Thanks. However, in this case, it is not CC0. As you can see in the description, the data comes from the UCI repository, which did not list a license with it. Hence, this falls under the CC Public Domain mark: 

_Using the Public Domain Mark, you can mark a work that is free of known copyright restrictions and clearly convey that status. When applied properly, the PDM allows the work to be easily discovered, and provides valuable information about the work._

I'm not a legal expert though. Are we (or the dataset uploader) wrong about this?

Thanks.

**Comment by egonw** [comment]
The CC Public Domain Mark sounds fine. The (correct) link for that is: https://creativecommons.org/publicdomain/mark/1.0/

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#586
