### ISSUE TITLE
Nothing happens when creating a new task

### ISSUE THREAD

**Issue by DraXus** [openml/website#8]
I'm creating a new task with the configuration shown in the attached image, but when I click submit, the website is refreshed but nothing happens. No error, no confirmation, and the task is not created.

![creating-task](https://cloud.githubusercontent.com/assets/2436/4649796/0103f63c-548e-11e4-9232-c6e41981079d.PNG)

**Comment by HeidiSeibold** [comment]
I have a similar issue: I do get a response, but it does not look very pretty (see bottom left corner)

![image](https://cloud.githubusercontent.com/assets/14146757/23406350/d267126e-fdbe-11e6-979d-3640c75787c4.png)

**Comment by joaquinvanschoren** [comment]
Duplicate #43
