### ISSUE TITLE
Download activity seems incorrect

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#80]
[My download activity](http://www.openml.org/u/970) seems too low. Only in the last few days I have downloaded many tasks (way more than 15).

![image](https://cloud.githubusercontent.com/assets/14146757/21053972/fa793f8e-be2b-11e6-910e-73a4842ff0f4.png)

**Comment by joaquinvanschoren** [comment]
seems ok now

**Comment by joaquinvanschoren** [comment]
This issue was moved to openml/OpenML#583
