### ISSUE TITLE
Runs don't show up in study

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#81]
When I tag a [run](http://www.openml.org/r/1845985) with study_38, shouldn't it be added to the [study](http://www.openml.org/s/38)?

**Comment by joaquinvanschoren** [comment]
Yes it should. I'll check it asap. 

Sorry for being slow, with NIPS last week and the resulting work backlog I'm struggling to keep up, but will address all your issues this week or next.

**Comment by HeidiSeibold** [comment]
No worries, I am not in a hurry ;)

**Comment by joaquinvanschoren** [comment]
Should be fixed :). Tested it and it works.
