### ISSUE TITLE
Problem with tasks website

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#88]
I am having major issues with
https://www.openml.org/search?type=task

First I got this:

![image](https://cloud.githubusercontent.com/assets/14146757/22684200/a08c7152-ed1b-11e6-841a-a74907acc2de.png)

Now it looks fine but I cannot open the side bar
![image](https://cloud.githubusercontent.com/assets/14146757/22684389/6e8a0114-ed1c-11e6-975c-d4b68de55f1a.png)

Is this related to openml/openml-r#310 ?

**Comment by HeidiSeibold** [comment]
Also when I try to sort the tasks, it redirects me to the main page https://www.openml.org/#

**Comment by joaquinvanschoren** [comment]
We updated the server today. This seems to be solved :)

**Comment by HeidiSeibold** [comment]
Thanks!
