### ISSUE TITLE
I'd like to know all data sets that are not connected to a task

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/website#96]
For the useR tutorial it would be nice to have a practical such as

*You received a data set ID. Create a sensible task for this data set.*

For this I need a list of data set IDs for which there are no tasks yet.

**Comment by berndbischl** [comment]
cant you simply do that in R with the R package? list both, then compute that?

**Comment by HeidiSeibold** [comment]
You're right, never mind

```
library("OpenML")

dat_info <- listOMLDataSets(limit = 99999)
tsk_info <- listOMLTasks(limit = 99999)

dat_has_task <- dat_info$data.id %in% tsk_info$data.id
dat_no_task <- which(!dat_has_task)
```

Just FYI, as of now there are 28
